### ISSUE TITLE
Building causes errors

### ISSUE THREAD

**Issue by ken-morel** [silvncr/osutool#1]
build causes errors due to not install colorama

**Comment by ken-morel** [comment]
this is due to build creating an isolated environment and importing your module **without** dependencies

**Comment by ken-morel** [comment]
I found a turnaround at #2

**Comment by riverpaper** [comment]
i haven't been able to get it to work ([stackoverflow](https://stackoverflow.com/q/78506013/16210754)), so thank you for trying to help.

i merged your changes, and it still fails (https://github.com/silvncr/osutool/actions/runs/9333697215/job/25690982940).

idk how to fix it, even though i've published modules the same way before.

**Comment by ken-morel** [comment]
Ow, realy sorry

**Comment by ken-morel** [comment]
The turnaround I found was working localy since setuptools was already installed, I will please you to merge this second pull

**Comment by riverpaper** [comment]
i'm willing to try something else if you want me to

**Comment by ken-morel** [comment]
View the latest pull please

**Comment by ken-morel** [comment]
> i haven't been able to get it to work ([stackoverflow](https://stackoverflow.com/q/78506013/16210754)), so thank you for trying to help.
> 
> i merged your changes, and it still fails (https://github.com/silvncr/osutool/actions/runs/9333697215/job/25690982940).
> 
> idk how to fix it, even though i've published modules the same way before.

well... saw your other packages as qrs and jarguments, but I do not yet see the difference

**Comment by riverpaper** [comment]
yeah, i'm using the exact same setup for those and they work fine. that's why i'm so confused about this one.

**Comment by ken-morel** [comment]
Please try merging this pull #4

**Comment by ken-morel** [comment]
Ow I see the latest workflow run, did not happen to me but, could you try adding the `pytest_runner` to the pip install in the workflow?

**Comment by ken-morel** [comment]
https://github.com/silvncr/osutool/edit/main/.github/workflows/python-publish.yml

**Comment by riverpaper** [comment]
https://github.com/silvncr/osutool/commit/ec49e56a11bdaf428fe98f62cefd214dc635322f

trying now

**Comment by riverpaper** [comment]
https://github.com/silvncr/osutool/actions/runs/9334155760/job/25692009749

**Comment by ken-morel** [comment]
I see, going further!, adding `wheel` now..

**Comment by ken-morel** [comment]
Also you could temporarily change the workflows `on` to push as:
```yaml
on: push
```

so you do not have to create a release each time.

**Comment by riverpaper** [comment]
https://github.com/silvncr/osutool/actions/runs/9334229545/job/25692193983

it worked! thank you so much for your help!

**Comment by ken-morel** [comment]
Wow, my **first** pull request is a success, or... half a success but I am still happy.

**Comment by riverpaper** [comment]
i'm going to credit you on my stackoverflow post, too

**Comment by ken-morel** [comment]
Ow too good! maybe will I have more than one reputation now!

**Comment by ken-morel** [comment]
Ow much better I had 25pts and more that 5 badges and privileges, really thanks!
